<?php
/**
 * Created by PhpStorm.
 * User: zhezhao
 * Date: 2016/8/11
 * Time: 16:17
 */
define("APP_PATH",dirname(__DIR__));

define("Lib_PATH",APP_PATH.DIRECTORY_SEPARATOR."libs".DIRECTORY_SEPARATOR);
define("WebApp_PATH",APP_PATH.DIRECTORY_SEPARATOR."webapp".DIRECTORY_SEPARATOR);
define("APPLICATION",APP_PATH.DIRECTORY_SEPARATOR."application".DIRECTORY_SEPARATOR);
define("Resource_PATH",APP_PATH.DIRECTORY_SEPARATOR."resource".DIRECTORY_SEPARATOR);
define("Log_PATH",APP_PATH.DIRECTORY_SEPARATOR."log".DIRECTORY_SEPARATOR);

define("Controller_PATH",APPLICATION."controller".DIRECTORY_SEPARATOR);
define("Model_PATH",APPLICATION."model".DIRECTORY_SEPARATOR);
define("View_PATH",APPLICATION."view".DIRECTORY_SEPARATOR);
//兼容CI框架
define("BASEPATH",Lib_PATH);